# Site
repository: g2ailhammubarok/g2ailhammubarok.github.io
favicon: images/favicon.ico

# Personal info
name: Ilham Mubarok
title: IT Student
email: g2a.ilhammubarok@gmail.com
website: www.github.com/g2ailhammubarok

# Social links
# twitter_username: facespics
github_username:  g2ailhammubarok
# dribbble_username: 
# facebook_username: 
# flickr_username: 
instagram_username: ilham.bara
linkedin_username: ilhambara
# pinterest_username: 
# youtube_username: globalmtb
# googleplus_username: 

# About Section
# about_title: About Me
about_profile_image: images/profile-me.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Bara and I'm an Informatics Engineering Student. I prefer to be known as a Coder instead of Programmer, cause i just write a code. I put my interest on eating various type of meatball.

  I am most skilled in: <mark>HTML</mark> and <mark>Doing Nothing</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Eating
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
